### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by denisk20** [Qkyrie/Markdown2Pdf#2]
Hi!
First of all, thank you for the great library!
Can you consider licencing under LGPL instead of AGPL so that we could use it in our project? It looks like this would be fine since flying-saucer-pdf uses LGPL as well.

**Comment by Qkyrie** [comment]
no problem at all :)

**Comment by Qkyrie** [comment]
License has been updated, new version not deployed yet to mvn repo, but it doesn't contain new functionality.  

You have written permission hereby to do whatever you want with the code.

regards
Q

**Comment by denisk20** [comment]
Thank you so much! When you're ready to upload to maven you could also update flying-saucer-pdf's version to `9.1.1` (currently it's `9.0.3`).
Thanks again for the great work!

**Comment by Qkyrie** [comment]
new version has been released, as per request the flying-saucer-pdf dependency has been udpated to 9.1.1

`    <dependency>
            <groupId>eu.de-swaef.pdf</groupId>
            <artifactId>Markdown2Pdf</artifactId>
            <version>2.0.0</version>
        </dependency>`

**Comment by denisk20** [comment]
it looks like [the recent maven version](http://search.maven.org/#artifactdetails%7Ceu.de-swaef.pdf%7CMarkdown2Pdf%7C2.0.0%7Cjar) has picked Apache 2.0 instead of LGPL:
![image](https://cloud.githubusercontent.com/assets/3080318/22596068/c0eaa02c-ea32-11e6-8489-fe7b9e489399.png)

**Comment by Qkyrie** [comment]
```
<dependency>
    <groupId>eu.de-swaef.pdf</groupId>
    <artifactId>Markdown2Pdf</artifactId>
    <version>2.0.1</version>
</dependency>
```
