### ISSUE TITLE
Chinese words will turn to be garbled after converting

### ISSUE THREAD

**Issue by stonenice** [Qkyrie/Markdown2Pdf#5]
Recently, I want to develop a tool to convert document with markdown syntax. so, I use your library to help me to archive it. Unfortunately, the garbled code makes me confused. If the library supports to set the charset , maybe I will solve it by myself!

**Comment by aimaodeyuer** [comment]
@stonenice have u solved this problem.if u solve it.@me,plz.

**Comment by raphapy** [comment]
@stonenice, @aimaodeyuer  Hi, [this pull request](https://github.com/Qkyrie/Markdown2Pdf/pull/6) resolve most of the charset related issues. But, I think chinese characters support relies on iText and is necesary to upgrade its version in order to allow users put itext-asian-jar in their classpath
